#!/usr/bin/env python3
"""Plot x_qp(t) for one simulated aluminum junction patch.

This implements the gamma-impact analysis described by Yelton et al.,
Phys. Rev. B 110, 024519 (2024), Eqs. (1) and (5).

The G4CMP thin-film model records N_qp*Delta as deposited energy.  The
sensitive-detector output has already converted that energy to the
``QPs Created`` column.  Each row represents one instantaneous Kaplan
cascade, not one individually tracked quasiparticle.
"""

from __future__ import annotations

import csv
from pathlib import Path

try:
    import matplotlib.pyplot as plt
    import numpy as np
    from matplotlib.ticker import AutoMinorLocator, MultipleLocator
except ModuleNotFoundError as error:
    raise SystemExit(
        "This script requires NumPy and Matplotlib. Install them with:\n"
        "  python3 -m pip install numpy matplotlib"
    ) from error


# ---------------------------------------------------------------------------
# User settings
# ---------------------------------------------------------------------------

SCRIPT_DIRECTORY = Path(__file__).resolve().parent

# Input CSV/TXT file produced by ChargeElectrodeSensitivity.  Use a combined
# worker file here if the simulation was multithreaded.
INPUT_FILE = SCRIPT_DIRECTORY.parent / "results" / "qp_creation_noCu_best.txt"

# Written by ChargeRunAction.  With SIMULATED_EH_PAIRS=None, the analysis
# requires this manifest to certify that the requested run completed.
RUN_SUMMARY_FILE = SCRIPT_DIRECTORY.parent / "results" / "run_summary_qp_creation_noCu_best.txt"

# Select the aluminum patches by their center positions.  Figure 8 uses a
# near patch at (400, 200) um (solid line) and a far patch at (3800, 200) um
# (dashed line), both plotted on the same axes.
NEAR_PATCH_CENTER_UM = (400.0, 200.0)
FAR_PATCH_CENTER_UM = (3800.0, 200.0)

# Histogram and plot settings.
TIME_BIN_WIDTH_US = 0.1
PLOT_END_TIME_US = 350.0
OUTPUT_FILE = SCRIPT_DIRECTORY / "xqp_vs_time.png"

# Figure 8 uses red for no back-side down-converting film, blue for 10-um Cu,
# solid lines for a near patch, and dashed lines for a far patch.
LINE_COLOR = "red"
NEAR_LINE_STYLE = "-"
FAR_LINE_STYLE = "--"
LINE_WIDTH = 2.2

# Figure 8 labels the linear vertical axis in units of 10^-5.
XQP_DISPLAY_SCALE = 1.0e5

# Leave this as None to read and validate the completed count from
# RUN_SUMMARY_FILE.  A positive integer is available only as an explicit
# override for imported data which has no run manifest.
SIMULATED_EH_PAIRS: int | None = None

# Paper inputs for a representative 100-keV gamma impact.
GAMMA_DEPOSIT_ENERGY_EV = 100_000.0
ENERGY_PER_EH_PAIR_EV = 3.6

# The simulation uses a 10x10 um^2 patch, whereas the physical junction
# footprint used for normalization is 5x1 um^2.  The simulated QP yield is
# therefore divided by 20 (paper Sec. II).
SIMULATED_TO_PHYSICAL_AREA_FACTOR = 20.0
PHYSICAL_ELECTRODE_X_UM = 5.0
PHYSICAL_ELECTRODE_Y_UM = 1.0
PHYSICAL_ELECTRODE_THICKNESS_UM = 0.12

# Cooper-pair density and loss rates used by the paper.
COOPER_PAIR_DENSITY_PER_UM3 = 4.0e6
TRAPPING_RATE_PER_US = 5.0e-2       # s in Eq. (1)
RECOMBINATION_RATE_PER_US = 100.0   # r = 1/(10 ns)


REQUIRED_COLUMNS = {
    "Run ID",
    "Event ID",
    "QP Creation Time [ns]",
    "Patch Center X [um]",
    "Patch Center Y [um]",
    "QPs Created",
}


def load_selected_patch(
    path: Path, patch_center_x_um: float, patch_center_y_um: float
) -> tuple[np.ndarray, np.ndarray]:
    """Load QP creation times/counts for the requested patch."""
    if not path.is_file():
        raise FileNotFoundError(
            f"Input file does not exist: {path}\n"
            "Set INPUT_FILE near the top of this script."
        )

    creation_times_us: list[float] = []
    qp_counts: list[float] = []
    records_seen = False

    with path.open(newline="") as input_stream:
        reader = csv.DictReader(input_stream)
        columns = set(reader.fieldnames or [])
        missing = REQUIRED_COLUMNS - columns
        if missing:
            missing_text = ", ".join(sorted(missing))
            raise ValueError(
                f"{path} is missing required columns: {missing_text}. "
                "Use output generated by the current sensitivity code."
            )

        for row in reader:
            records_seen = True

            # DictReader fills columns missing from a short/truncated record
            # with None.  Report damaged simulation output explicitly instead
            # of passing that value to float(), which produces an unhelpful
            # TypeError with no indication of the offending record.
            missing_values = [
                column
                for column in sorted(REQUIRED_COLUMNS)
                if row.get(column) is None or not row[column].strip()
            ]
            if missing_values:
                missing_text = ", ".join(missing_values)
                raise ValueError(
                    f"Malformed record at {path}:{reader.line_num}: missing "
                    f"value(s) for {missing_text}. The simulation output is "
                    "truncated or was combined before all workers finished. "
                    "Complete the simulation and rebuild the combined hit file."
                )

            try:
                center_x_um = float(row["Patch Center X [um]"])
                center_y_um = float(row["Patch Center Y [um]"])
                creation_time_us = float(row["QP Creation Time [ns]"]) / 1000.0
                qp_count = float(row["QPs Created"])
            except ValueError as error:
                raise ValueError(
                    f"Malformed numeric value at {path}:{reader.line_num}."
                ) from error

            numeric_values = (
                center_x_um,
                center_y_um,
                creation_time_us,
                qp_count,
            )
            if not all(np.isfinite(value) for value in numeric_values):
                raise ValueError(
                    f"Non-finite numeric value at {path}:{reader.line_num}."
                )

            selected = (
                np.isclose(center_x_um, patch_center_x_um, atol=1.0e-6)
                and np.isclose(center_y_um, patch_center_y_um, atol=1.0e-6)
            )
            if selected:
                creation_times_us.append(creation_time_us)
                qp_counts.append(qp_count)

    if not records_seen:
        raise ValueError(f"No simulation events were found in {path}.")
    if not creation_times_us:
        raise ValueError(
            "No QP creation records were found for patch center "
            f"({patch_center_x_um:g}, {patch_center_y_um:g}) um."
        )

    return np.asarray(creation_times_us), np.asarray(qp_counts)


def load_completed_eh_pairs(path: Path) -> int:
    """Return the certified event count from the master run manifest."""
    if not path.is_file():
        raise FileNotFoundError(
            f"Run summary does not exist: {path}\n"
            "The hit file cannot reveal events which produced zero QPs. "
            "Rerun the simulation with ChargeRunAction enabled, or set "
            "SIMULATED_EH_PAIRS explicitly for independently verified data."
        )

    with path.open(newline="") as summary_stream:
        rows = list(csv.DictReader(summary_stream))
    if len(rows) != 1:
        raise ValueError(f"Expected one run-summary row in {path}.")

    row = rows[0]
    requested = int(row["Requested Events"])
    completed = int(row["Completed Events"])
    complete = int(row["Complete"]) == 1
    if not complete or completed != requested:
        raise RuntimeError(
            f"Simulation run is incomplete: {completed}/{requested} events. "
            "Do not calculate x_qp from this partial output."
        )
    return completed


def calculate_xqp(
    creation_times_us: np.ndarray,
    qp_counts: np.ndarray,
    simulated_eh_pairs: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Construct g(t) with paper Eq. (5), then solve paper Eq. (1)."""
    if TIME_BIN_WIDTH_US <= 0.0 or PLOT_END_TIME_US <= 0.0:
        raise ValueError("TIME_BIN_WIDTH_US and PLOT_END_TIME_US must be positive.")
    if simulated_eh_pairs <= 0:
        raise ValueError("The number of simulated e-/h+ pairs must be positive.")

    number_of_bins = int(np.ceil(PLOT_END_TIME_US / TIME_BIN_WIDTH_US))
    time_edges_us = np.arange(number_of_bins + 1) * TIME_BIN_WIDTH_US

    # N_qp(t): sum the number of QPs from every cascade in each time bin.
    simulated_nqp, _ = np.histogram(
        creation_times_us,
        bins=time_edges_us,
        weights=qp_counts,
    )

    gamma_eh_pairs = int(GAMMA_DEPOSIT_ENERGY_EV / ENERGY_PER_EH_PAIR_EV)
    physical_electrode_volume_um3 = (
        PHYSICAL_ELECTRODE_X_UM
        * PHYSICAL_ELECTRODE_Y_UM
        * PHYSICAL_ELECTRODE_THICKNESS_UM
    )

    # Equation (5), including the factor-of-20 patch-area correction:
    #
    # g(t) = [N_qp(t)/(N_eh^sim n_cp V Delta_t)] * N_eh^gamma.
    physical_nqp = simulated_nqp / SIMULATED_TO_PHYSICAL_AREA_FACTOR
    gamma_scaled_nqp = physical_nqp * gamma_eh_pairs / simulated_eh_pairs
    generation_rate_per_us = gamma_scaled_nqp / (
        COOPER_PAIR_DENSITY_PER_UM3
        * physical_electrode_volume_um3
        * TIME_BIN_WIDTH_US
    )

    # Forward Euler solution of Eq. (1):
    # dx_qp/dt = -r*x_qp^2 - s*x_qp + g(t).
    xqp = np.zeros(number_of_bins + 1)
    for index, generation_rate in enumerate(generation_rate_per_us):
        loss_rate = (
            RECOMBINATION_RATE_PER_US * xqp[index] ** 2
            + TRAPPING_RATE_PER_US * xqp[index]
        )
        xqp[index + 1] = max(
            0.0,
            xqp[index]
            + TIME_BIN_WIDTH_US * (generation_rate - loss_rate),
        )

    return time_edges_us, xqp, generation_rate_per_us


def main() -> None:
    simulated_eh_pairs = (
        load_completed_eh_pairs(RUN_SUMMARY_FILE)
        if SIMULATED_EH_PAIRS is None
        else SIMULATED_EH_PAIRS
    )

    patches = (
        ("near", NEAR_PATCH_CENTER_UM, NEAR_LINE_STYLE),
        ("far", FAR_PATCH_CENTER_UM, FAR_LINE_STYLE),
    )

    results = []
    for label, (center_x_um, center_y_um), linestyle in patches:
        creation_times_us, qp_counts = load_selected_patch(
            INPUT_FILE, center_x_um, center_y_um
        )
        time_us, xqp, _ = calculate_xqp(
            creation_times_us,
            qp_counts,
            simulated_eh_pairs,
        )
        results.append(
            (label, center_x_um, center_y_um, linestyle, creation_times_us, time_us, xqp)
        )

    plt.rcParams.update(
        {
            "font.family": "serif",
            "font.size": 12,
            "mathtext.fontset": "cm",
            "axes.linewidth": 1.0,
        }
    )

    figure, axis = plt.subplots(figsize=(6.0, 3.6))
    for label, center_x_um, center_y_um, linestyle, _, time_us, xqp in results:
        axis.plot(
            time_us,
            xqp * XQP_DISPLAY_SCALE,
            color=LINE_COLOR,
            linestyle=linestyle,
            linewidth=LINE_WIDTH,
            label=rf"({center_x_um:g}, {center_y_um:g}) $\mu$m ({label})",
        )
    axis.set_xlabel(r"Time ($\mu$s)")
    axis.set_ylabel(r"$x_{\mathrm{qp}}\ (10^{-5})$")
    axis.set_xlim(0.0, PLOT_END_TIME_US)
    axis.set_ylim(bottom=0.0)

    # Match the boxed, inward-facing major/minor ticks in Fig. 8.
    axis.xaxis.set_major_locator(MultipleLocator(100.0))
    axis.xaxis.set_minor_locator(AutoMinorLocator(5))
    axis.yaxis.set_minor_locator(AutoMinorLocator(5))
    axis.tick_params(
        which="major",
        direction="in",
        top=True,
        right=True,
        length=6,
        width=1.0,
    )
    axis.tick_params(
        which="minor",
        direction="in",
        top=True,
        right=True,
        length=3,
        width=0.8,
    )

    axis.legend(loc="upper right", frameon=False, fontsize=10)

    figure.tight_layout()
    figure.savefig(OUTPUT_FILE, dpi=200)

    gamma_eh_pairs = int(GAMMA_DEPOSIT_ENERGY_EV / ENERGY_PER_EH_PAIR_EV)
    print(f"Input file: {INPUT_FILE}")
    print(f"Simulated e-/h+ pairs used for scaling: {simulated_eh_pairs}")
    print(f"Target e-/h+ pairs for gamma impact: {gamma_eh_pairs}")
    for label, center_x_um, center_y_um, _, creation_times_us, _, xqp in results:
        print(
            f"Patch ({label}) center: ({center_x_um:g}, {center_y_um:g}) um, "
            f"cascade records: {creation_times_us.size}, "
            f"peak x_qp: {np.max(xqp):.6g}"
        )
    print(f"Saved plot: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
